from mosaics import *
import ast
import json
import numpy as np
import pandas as pd
from pathlib import Path
from datetime import datetime


def parse_mosaic(mosaic):
    """
    Convert a CSV Mosaic cell, Mosaic, Matrix, list, or numpy array to an int array.

    CSV files generated by data_gen.py store mosaics as strings like:
    "[[2, 5, 1], [6, 0, 3], [3, 4, 0]]"
    """
    if isinstance(mosaic, str):
        mosaic = ast.literal_eval(mosaic)
    elif isinstance(mosaic, Mosaic):
        mosaic = mosaic.matrixRepresentation

    if hasattr(mosaic, "tolist"):
        mosaic = mosaic.tolist()

    arr = np.asarray(mosaic, dtype=np.int64)
    if arr.ndim != 2:
        raise ValueError(f"mosaic must be a 2D matrix, got shape {arr.shape}")
    if arr.shape[0] != arr.shape[1]:
        raise ValueError(f"mosaic must be square, got shape {arr.shape}")
    if np.any((arr < 0) | (arr >= 11)):
        raise ValueError("mosaic entries must be integers from 0 to 10")

    return arr


def mosaic_to_onehot(mosaic):
    """
    Convert an n x n integer mosaic to an n x n x 11 one-hot array.

    Accepts the string format stored in generated CSV files.
    """
    arr = parse_mosaic(mosaic)
    return np.eye(11, dtype=np.float32)[arr]


def onehot_to_mosaic(onehot):
    """
    Inverse: n x n x 11 one-hot/logit/probability array -> n x n integer mosaic.

    Takes argmax along the channel axis.
    """
    arr = np.asarray(onehot)
    if arr.ndim < 3 or arr.shape[-1] != 11:
        raise ValueError(f"onehot must have final dimension 11, got shape {arr.shape}")

    return np.argmax(arr, axis=-1).astype(np.int64)


def load_mosaic_csv(csv_path, label_col=None, onehot=True):
    """
    Load a data_gen.py CSV into model-ready arrays.

    Returns:
        X: shape (samples, n, n, 11) when onehot=True, else (samples, n, n)
        y: shape (samples,)
    """
    df = pd.read_csv(csv_path)
    if "Mosaic" not in df.columns:
        raise ValueError("CSV must contain a 'Mosaic' column")

    if label_col is None:
        label_cols = [col for col in df.columns if col != "Mosaic"]
        if len(label_cols) != 1:
            raise ValueError("label_col is required when CSV has multiple label columns")
        label_col = label_cols[0]

    mosaics = [parse_mosaic(value) for value in df["Mosaic"]]
    X = np.stack([mosaic_to_onehot(m) for m in mosaics]) if onehot else np.stack(mosaics)
    y = df[label_col].to_numpy(dtype=np.int64)

    return X, y


def _train_test_split(X, y, test_fraction=0.2, seed=42):
    """Small stratified split without adding a scikit-learn dependency."""
    rng = np.random.default_rng(seed)
    train_indices = []
    test_indices = []

    for label in np.unique(y):
        label_indices = np.where(y == label)[0]
        rng.shuffle(label_indices)
        test_count = max(1, int(round(len(label_indices) * test_fraction)))
        test_indices.extend(label_indices[:test_count])
        train_indices.extend(label_indices[test_count:])

    rng.shuffle(train_indices)
    rng.shuffle(test_indices)

    return X[train_indices], X[test_indices], y[train_indices], y[test_indices]


def _confusion_counts(y_true, y_pred):
    true_positive = int(np.sum((y_true == 1) & (y_pred == 1)))
    true_negative = int(np.sum((y_true == 0) & (y_pred == 0)))
    false_positive = int(np.sum((y_true == 0) & (y_pred == 1)))
    false_negative = int(np.sum((y_true == 1) & (y_pred == 0)))
    return true_positive, true_negative, false_positive, false_negative


def _binary_metrics(y_true, y_pred):
    tp, tn, fp, fn = _confusion_counts(y_true, y_pred)
    accuracy = (tp + tn) / len(y_true) if len(y_true) else 0.0
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    specificity = tn / (tn + fp) if tn + fp else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    balanced_accuracy = (recall + specificity) / 2
    return {
        "accuracy": float(accuracy),
        "precision": float(precision),
        "recall": float(recall),
        "specificity": float(specificity),
        "f1": float(f1),
        "balanced_accuracy": float(balanced_accuracy),
        "confusion_counts": {
            "true_positive": tp,
            "true_negative": tn,
            "false_positive": fp,
            "false_negative": fn,
        },
    }


def _class_counts(y):
    values, counts = np.unique(y, return_counts=True)
    return {str(int(value)): int(count) for value, count in zip(values, counts)}


def _save_training_statistics(history, stats, prefix="training"):
    with open(f"{prefix}_statistics.json", "w", encoding="utf-8") as f:
        json.dump(stats, f, indent=2)
    history_df = pd.DataFrame(history.history)
    history_df.insert(0, "epoch", np.arange(1, len(history_df) + 1))
    history_df.to_csv(f"{prefix}_history.csv", index=False)

    import matplotlib.pyplot as plt

    epochs = range(1, len(history.history["loss"]) + 1)
    _, axes = plt.subplots(1, 2, figsize=(10, 4))

    axes[0].plot(epochs, history.history["loss"], label="train")
    axes[0].plot(epochs, history.history["val_loss"], label="validation")
    axes[0].set_title("Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Binary cross-entropy")
    axes[0].legend()

    axes[1].plot(epochs, history.history["accuracy"], label="train")
    axes[1].plot(epochs, history.history["val_accuracy"], label="validation")
    axes[1].set_title("Accuracy")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Accuracy")
    axes[1].legend()

    plt.tight_layout()
    plt.savefig(f"{prefix}_curves.png", dpi=150)
    plt.close()


def _save_prediction_statistics(y_test, probabilities, predictions, path):
    prediction_df = pd.DataFrame(
        {
            "actual": y_test.astype(int),
            "predicted": predictions.astype(int),
            "p_label_1": probabilities,
            "correct": (y_test == predictions).astype(int),
        }
    )
    prediction_df.to_csv(path, index=False)


def _safe_name(value):
    return "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in str(value))


def _cache_run(model, history, stats, y_test, probabilities, predictions, cache_dir="cnn_cache"):
    root = Path(cache_dir)
    root.mkdir(exist_ok=True)

    csv_stem = Path(stats["csv_path"]).stem
    label = stats["label_col"] or "auto_label"
    shape = "x".join(str(part) for part in stats["input_shape"])
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    val_acc = f"{stats['final_validation_accuracy']:.3f}".replace(".", "p")
    run_name = _safe_name(
        f"{timestamp}_{csv_stem}_{label}_{shape}_ep{stats['trained_epochs']}of{stats['requested_epochs']}"
        f"_train{stats['train_samples']}_test{stats['test_samples']}_valacc{val_acc}"
    )
    run_dir = root / run_name
    suffix = 1
    while run_dir.exists():
        suffix += 1
        run_dir = root / f"{run_name}_{suffix}"
    run_dir.mkdir()

    weights_path = run_dir / "model.weights.h5"
    model_path = run_dir / "model.keras"
    stats_path = run_dir / "statistics.json"
    curves_prefix = str(run_dir / "training")
    predictions_path = run_dir / "test_predictions.csv"

    stats["cache_path"] = str(run_dir)
    model.save_weights(weights_path)
    model.save(model_path)
    _save_training_statistics(history, stats, prefix=curves_prefix)
    _save_prediction_statistics(y_test, probabilities, predictions, predictions_path)

    with open(stats_path, "w", encoding="utf-8") as f:
        json.dump(stats, f, indent=2)

    return run_dir


def train_ccnn(
    csv_path,
    label_col=None,
    epochs=15,
    batch_size=16,
    test_fraction=0.2,
    seed=42,
    statistics=True,
    cache=True,
    early_stopping=True,
    patience=10,
    min_delta=0.0,
):
    """
    Train a simple convolutional classifier on a generated mosaic CSV.

    The input is the one-hot encoding from load_mosaic_csv(); labels are the
    single non-Mosaic column unless label_col is provided. When statistics=True,
    writes training_statistics.json and training_curves.png to the working directory.
    When cache=True, saves weights, the full model, statistics, and curves under cnn_cache/.
    early_stopping=True guards against overfitting by restoring the best val_loss weights.
    """
    try:
        import tensorflow as tf
    except ImportError as exc:
        raise ImportError(
            "train_ccnn requires a working TensorFlow install; install or repair TensorFlow"
        ) from exc

    X, y = load_mosaic_csv(csv_path, label_col=label_col, onehot=True)
    X_train, X_test, y_train, y_test = _train_test_split(
        X, y, test_fraction=test_fraction, seed=seed
    )

    tf.keras.utils.set_random_seed(seed)
    # Previous pooled architecture:
    # model = tf.keras.Sequential(
    #     [
    #         tf.keras.layers.Input(shape=X.shape[1:]),
    #         tf.keras.layers.Conv2D(32, 3, padding="same", activation="relu"),
    #         tf.keras.layers.MaxPooling2D(),
    #         tf.keras.layers.Conv2D(64, 3, padding="same", activation="relu"),
    #         tf.keras.layers.GlobalAveragePooling2D(),
    #         tf.keras.layers.Dense(32, activation="relu"),
    #         tf.keras.layers.Dense(1, activation="sigmoid"),
    #     ]
    # )

    model = tf.keras.Sequential(
        [
            tf.keras.layers.Input(shape=X.shape[1:]),
            tf.keras.layers.Conv2D(32, 3, padding="same", activation="relu"),
            tf.keras.layers.Conv2D(64, 3, padding="same", activation="relu"),
            tf.keras.layers.Conv2D(64, 3, padding="same", activation="relu"),
            tf.keras.layers.Conv2D(32, 3, padding="same", activation="relu"),
            tf.keras.layers.GlobalAveragePooling2D(),
            tf.keras.layers.Dense(1, activation="sigmoid"),
        ]
    )
    model.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )

    callbacks = []
    if early_stopping:
        callbacks.append(
            tf.keras.callbacks.EarlyStopping(
                monitor="val_loss",
                patience=patience,
                min_delta=min_delta,
                restore_best_weights=True,
            )
        )

    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_test, y_test),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=1,
    )

    test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
    probabilities = model.predict(X_test, verbose=0).reshape(-1)
    predictions = (probabilities >= 0.5).astype(np.int64)

    metrics = _binary_metrics(y_test, predictions)
    tp = metrics["confusion_counts"]["true_positive"]
    tn = metrics["confusion_counts"]["true_negative"]
    fp = metrics["confusion_counts"]["false_positive"]
    fn = metrics["confusion_counts"]["false_negative"]
    trained_epochs = len(history.history["loss"])
    best_val_loss_index = int(np.argmin(history.history["val_loss"]))
    best_val_accuracy_index = int(np.argmax(history.history["val_accuracy"]))
    train_val_accuracy_gap = (
        history.history["accuracy"][-1] - history.history["val_accuracy"][-1]
    )
    train_val_loss_gap = history.history["val_loss"][-1] - history.history["loss"][-1]
    stats = {
        "csv_path": str(csv_path),
        "label_col": label_col,
        "requested_epochs": epochs,
        "trained_epochs": trained_epochs,
        "batch_size": batch_size,
        "test_fraction": test_fraction,
        "seed": seed,
        "early_stopping": {
            "enabled": early_stopping,
            "monitor": "val_loss",
            "patience": patience,
            "min_delta": min_delta,
            "restore_best_weights": True,
            "stopped_early": trained_epochs < epochs,
        },
        "train_samples": int(len(X_train)),
        "test_samples": int(len(X_test)),
        "total_samples": int(len(X)),
        "train_class_counts": _class_counts(y_train),
        "test_class_counts": _class_counts(y_test),
        "input_shape": list(X.shape[1:]),
        "final_train_loss": float(history.history["loss"][-1]),
        "final_train_accuracy": float(history.history["accuracy"][-1]),
        "final_validation_loss": float(history.history["val_loss"][-1]),
        "final_validation_accuracy": float(history.history["val_accuracy"][-1]),
        "best_validation_loss": float(history.history["val_loss"][best_val_loss_index]),
        "best_validation_loss_epoch": best_val_loss_index + 1,
        "best_validation_accuracy": float(history.history["val_accuracy"][best_val_accuracy_index]),
        "best_validation_accuracy_epoch": best_val_accuracy_index + 1,
        "train_minus_validation_accuracy": float(train_val_accuracy_gap),
        "validation_minus_train_loss": float(train_val_loss_gap),
        "test_loss": float(test_loss),
        "test_accuracy": float(test_accuracy),
        "test_metrics": metrics,
        "prediction_probability_summary": {
            "mean": float(np.mean(probabilities)),
            "std": float(np.std(probabilities)),
            "min": float(np.min(probabilities)),
            "max": float(np.max(probabilities)),
            "mean_when_actual_0": float(np.mean(probabilities[y_test == 0]))
            if np.any(y_test == 0) else None,
            "mean_when_actual_1": float(np.mean(probabilities[y_test == 1]))
            if np.any(y_test == 1) else None,
        },
    }
    if cache:
        cache_path = _cache_run(model, history, stats, y_test, probabilities, predictions)

    print("\nTraining complete")
    print(f"samples: train={len(X_train)}, test={len(X_test)}")
    print(f"input shape: {X.shape[1:]}")
    print(f"trained epochs: {trained_epochs}/{epochs}")
    print(f"best validation loss: {stats['best_validation_loss']:.4f} at epoch {stats['best_validation_loss_epoch']}")
    print(f"final train accuracy: {history.history['accuracy'][-1]:.3f}")
    print(f"final validation accuracy: {history.history['val_accuracy'][-1]:.3f}")
    print(f"test loss: {test_loss:.4f}")
    print(f"test accuracy: {test_accuracy:.3f}")
    print(f"precision: {metrics['precision']:.3f}")
    print(f"recall: {metrics['recall']:.3f}")
    print(f"f1: {metrics['f1']:.3f}")
    print(f"specificity: {metrics['specificity']:.3f}")
    print(f"confusion counts: TP={tp}, TN={tn}, FP={fp}, FN={fn}")
    print("sample predictions:")
    for actual, probability, predicted in zip(y_test[:5], probabilities[:5], predictions[:5]):
        print(f"  actual={actual}, predicted={predicted}, p(label=1)={probability:.3f}")
    if statistics:
        _save_training_statistics(history, stats)
        _save_prediction_statistics(y_test, probabilities, predictions, "training_test_predictions.csv")
        print("saved statistics: training_statistics.json")
        print("saved history: training_history.csv")
        print("saved predictions: training_test_predictions.csv")
        print("saved graph: training_curves.png")
    if cache:
        print(f"cached model: {cache_path}")

    return model, history


if __name__ == "__main__":

    import argparse

    DATASET_DIR = Path("datasets")

    def dataset_path(data_type, dimension):
        return DATASET_DIR / data_type / f"dim_{dimension}.csv"

    def legacy_dataset_path(data_type):
        paths = {
            "unknot": "unknot_data.csv",
            "connected": "suitably_connected_data.csv",
            "has_crossing": "has_crossing_data.csv",
            "component": "component_data.csv",
            "trefoil": "trefoil_vs_unknot_data.csv",
        }
        return Path(paths[data_type])

    def resolve_dataset_path(data_type, dimension=None):
        if dimension is not None:
            path = dataset_path(data_type, dimension)
            if path.exists():
                return path
            legacy_path = legacy_dataset_path(data_type)
            if legacy_path.exists():
                print(f"{path} was not found; using legacy file {legacy_path}.")
                return legacy_path
            raise FileNotFoundError(f"No dataset found at {path}")

        data_dir = DATASET_DIR / data_type
        matches = sorted(data_dir.glob("dim_*.csv"), key=lambda p: p.stat().st_mtime, reverse=True)
        if matches:
            print(f"Using latest organized dataset: {matches[0]}")
            return matches[0]

        legacy_path = legacy_dataset_path(data_type)
        if legacy_path.exists():
            print(f"Using legacy dataset: {legacy_path}")
            return legacy_path
        raise FileNotFoundError(f"No dataset found for data_type={data_type}")

    parser = argparse.ArgumentParser()

    parser.add_argument("data_type", type=str)
    parser.add_argument("epochs", type=int)
    parser.add_argument("dimension", type=int, nargs="?")
    args = parser.parse_args()

    train_ccnn(resolve_dataset_path(args.data_type, args.dimension), epochs=args.epochs, statistics=True)
    



    # train_ccnn("component_data.csv", epochs=100, statistics=True)
