#!/usr/bin/env bash
# Finalize step: checkpoint + compress mosaics.db, publish as a GitHub release
# asset, and commit a per-release manifest back to the repo. Re-runnable.
set -uo pipefail

REPO_DIR="$HOME/KnotAI"
GH_REPO="andrew-tawfeek/KnotAI"
DB="mosaics.db"
VENV="$REPO_DIR/.venv/bin/python"
LOG=/tmp/knot_publish.log

cd "$REPO_DIR" || { echo "no repo dir"; exit 1; }
exec >>"$LOG" 2>&1
echo "=================================================="
echo "[publish] start $(date -u)"

[ -f "$DB" ] || { echo "[publish] no $DB; abort"; exit 1; }

TS=$(date -u +%Y%m%d-%H%M%S)
TAG="data-$TS"
ASSET_NAME="mosaics.db.${TS}.zst"
ZST="/tmp/${ASSET_NAME}"
COMMIT=$(git rev-parse HEAD)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Flush WAL into the main file so a single-file copy is complete.
echo "[publish] checkpointing WAL"
"$VENV" - <<'PY'
import sqlite3
c = sqlite3.connect("mosaics.db")
c.execute("PRAGMA wal_checkpoint(TRUNCATE)")
c.close()
PY

echo "[publish] compressing $DB -> $ZST"
zstd -T0 -19 -q -f -o "$ZST" "$DB" || { echo "[publish] zstd failed"; exit 1; }

SHA=$(sha256sum "$ZST" | awk '{print $1}')
DBSIZE=$(stat -c %s "$DB")
ZSIZE=$(stat -c %s "$ZST")
echo "[publish] db=${DBSIZE}B zst=${ZSIZE}B sha256=$SHA"

STATS=$("$VENV" tabulate_db.py stats 2>/dev/null)

# Per-release manifest (unique filename -> never a rebase conflict).
mkdir -p data_releases
MAN="data_releases/manifest-${TAG}.md"
{
  echo "# Mosaic dataset release \`$TAG\`"
  echo
  echo "_Auto-generated by the high-compute publish daemon._"
  echo
  echo "- Generated (UTC): $(date -u)"
  echo "- Source commit: \`$COMMIT\` (branch \`$BRANCH\`)"
  echo "- Uncompressed DB: $DBSIZE bytes"
  echo "- Release asset: \`$ASSET_NAME\` ($ZSIZE bytes)"
  echo "- sha256 (asset): \`$SHA\`"
  echo
  echo "## Restore"
  echo '```bash'
  echo "gh release download $TAG --repo $GH_REPO"
  echo "zstd -d $ASSET_NAME -o mosaics.db"
  echo '```'
  echo
  echo "## Per-dimension summary"
  echo '```'
  echo "$STATS"
  echo '```'
} > "$MAN"

echo "[publish] creating GitHub release $TAG"
gh release create "$TAG" "$ZST" \
  --repo "$GH_REPO" \
  --target "$COMMIT" \
  --title "Mosaic dataset $TS" \
  --notes-file "$MAN" || { echo "[publish] gh release create failed"; exit 1; }

echo "[publish] committing manifest + pushing"
git config user.name  "Andrew Tawfeek"
git config user.email "coffeeandproofs@gmail.com"
git add "$MAN"
git commit -m "Data release $TAG

Asset $ASSET_NAME uploaded to GitHub release $TAG.
sha256=$SHA

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>" || echo "[publish] nothing to commit"

pushed=0
for i in 1 2 3 4 5; do
  if git pull --rebase origin "$BRANCH" && git push origin "$BRANCH"; then pushed=1; break; fi
  echo "[publish] push attempt $i failed (race?); retrying"; sleep 5
done
[ "$pushed" -eq 1 ] && echo "[publish] manifest pushed" || echo "[publish] WARN: manifest push failed; release asset is still up"

rm -f "$ZST"
echo "[publish] done $(date -u)"
